class AppRoutes {
  static const splashScreen = '/splash_screen',
      onboardScreen = '/onboard_screen',
      scanScreen = '/scanning_screen',
      loginScreen = '/login_screen',
      singnUp = '/signup_screen',
      createAccount = '/create_account_screen',
      profileUpload = '/profile_upload_screen',
      resetPassword = '/reset_password_screen',
      healthMenu = '/health_menu_screen',
      homeScreen = '/home_screen',
      scanning = '/scanning_screen',
      congratulationsScreen = '/congratulation_screen',
      geustUserHistory = '/geust_user_history_screen',
      otpSignupScreen = '/otp_signup_screen',
      otpForgotScreen = '/otp_forgot_screen',
      addNewGeustScreen = '/add_new_guest_screen',
      mesurementScreen = "/measurement_model",
      guestHistoryDetails = "/guest_history_details",
      userHistoryList = "/user_history_data",
      userHealthDatails = "/user_health_details",
      allReportScreen = "/all_report_screen",
      guestHealthHistoryList = "/guest_health_history_list",
      analyzingHealthData = '/analyzing_health_data';
}
