class AppConstents {
  static const String
  commonFont = "Manrope",
  login = "Login",
  resetPassword = "Reset Password",
  confirm = "Confirm",
  email = "Email",
  password = "Password",
  confirmPassword = "Confirm Password",
  emailHint = "Please enter email",
  passHint = "Please enter password",
  confPassHint = "Please re-enter password",
  forgotPassword = "Forgot password?",
  donThaveAccoount = "Don’t have account?",
  signUp = "Sigup",
  gilroyBold = "Gilroy-Bold",
  gilroyMedium = "Gilroy-Medium",
  statusCode = "statusCode",
  response = "responseBody",
  upload = "Upload",
  continueBtn = "Continue",
  uploadPhotoHeading = "Upload photo for creating you account",
  name = "Name",
  gender = 'Gender',
  dob = 'Date of Birth',
  weight = "Weight (kg)",
  height = "Height (cm)",
  congractText = " Congratulation! Your Account created successfully. ",
  congractDis =
      " We are thrilled to extend a warm welcome to all newcomers and returning members alike. ",
  male = "Male",
  female = "Female",
  scanDiscri = "Measurement stared please hold face in the frame",
  createAccount = 'Create Account',
  termMeassaga =
      "Accept to the legal terms by clicking on the check box to be able to provide services";
}
